version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: product_catalog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
